ENV: ${self:provider.stage}
APPNAME: ${self:service}

CUSTOMERS_QUEUE: 'http://localhost:9324/queue/${self:custom.customers-sqs}'
# VINDI_WEBHOOK_QUEUE: 'http://localhost:9324/queue/${self:custom.vindi-webhook-sqs}'
PAYLOAD_QUEUE: 'http://localhost:9324/queue/${self:custom.payload-log-sqs}'

SUBSCRIPTIONS_QUEUE: 'http://localhost:9324/queue/${self:custom.subscriptions-sqs}'
CANCEL_SUBSCRIPTION_QUEUE: 'http://localhost:9324/queue/${self:custom.cancel-subscription-sqs}'
WH_SUBSCRIPTION_CANCELED_QUEUE: 'http://localhost:9324/queue/${self:custom.wh-subscription-canceled-sqs}'
WH_CHARGE_CREATED_QUEUE: 'http://localhost:9324/queue/${self:custom.wh-charge-created-sqs}'

WH_CHARGE_REJECTED_QUEUE: 'http://localhost:9324/queue/${self:custom.wh-charge-rejected-sqs}'
WH_BILL_CREATED_QUEUE: 'http://localhost:9324/queue/${self:custom.wh-bill-created-sqs}'
WH_BILL_CANCELED_QUEUE: 'http://localhost:9324/queue/${self:custom.wh-bill-canceled-sqs}'
WH_BILL_PAID_QUEUE: 'http://localhost:9324/queue/${self:custom.wh-bill-paid-sqs}'
WH_PAYMENT_PROFILE_CREATED_QUEUE: 'http://localhost:9324/queue/${self:custom.wh-payment-profile-created-sqs}'
WH_SUBSCRIPTION_CREATED_QUEUE: 'http://localhost:9324/queue/${self:custom.wh-subscription-created-sqs}'

EVENTS_EMPODERA_QUEUE: 'http://localhost:9324/queue/${self:custom.events-empodera-sqs}'
# EVENTS_LICENCIADOR_ERROR_HANDLING: 'http://localhost:9324/queue/${self:custom.licenciador_error_handling}'
EVENTS_LICENCIADOR_QUEUE: 'http://localhost:9324/queue/${self:custom.events-licenciador-sqs}'
EVENTS_PROTHEUS_QUEUE: 'http://localhost:9324/queue/${self:custom.events-protheus-sqs}'
EVENTS_PROTHEUS_CORP_QUEUE: 'http://localhost:9324/queue/${self:custom.events-protheus-corp-sqs}'
EVENTS_STORE_QUEUE: 'http://localhost:9324/queue/${self:custom.events-store-sqs}'
EVENTS_VINDI_QUEUE: 'http://localhost:9324/queue/${self:custom.events-vindi-sqs}'
EVENTS_MESSAGE_QUEUE: 'http://localhost:9324/queue/${self:custom.events-message-sqs}'
VERIFY_EVENTS_QUEUE: 'http://localhost:9324/queue/${self:custom.verify-events-sqs}'

MESSAGE_GATEWAY_QUEUE: 'http://localhost:9324/queue/${self:custom.message-gateway-sqs}'

# Services URL
LICENCIADOR_BASE_URL: 'https://tnedc617ag.execute-api.us-east-1.amazonaws.com/qa'
PROTHEUS_URL: 'https://apimprod.totvs.com.br/api-homologacao'
EMPODERA_BASE_URL: 'https://homolog-empodera.totvs.com/api/area/eleve'
VINDI_URL: 'https://sandbox-app.vindi.com.br/api/v1'
STORE_URL: 'https://tflow.mirror.store.totvs.com/api'
SERPRO_CPF_URL: 'https://gateway.apiserpro.serpro.gov.br/consulta-cpf-df-trial/v1/cpf'
SERPRO_CNPJ_URL: 'https://gateway.apiserpro.serpro.gov.br/consulta-cnpj-df-trial/v1/cnpj'
ZENVIA_URL: 'https://api-rest.zenvia.com/services'
PROTHEUS_CORP_URL: 'https://apimprod.totvs.com.br/api-homologacao'
CHAT_NOTIFY: 'https://chat.googleapis.com/v1/spaces/AAAAEdIOoZ4/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=6X359z2AU6GC4lSL097ouTDBv-JyTA0F86NCwniXeZk%3D'

PRODUCTID_VINDI: '53960'
PRODUCTID_RECOMPRA: '53960'

EMPODERA_KEY: ${ssm:${self:provider.stage}-empodera_key}
EMPODERA_TOKEN: ${ssm:${self:provider.stage}-empodera_token}
STORE_KEY: ${ssm:${self:provider.stage}-store_key}
STORE_TOKEN: ${ssm:${self:provider.stage}-store_token}
SERPRO_CNPJ_TOKEN: ${ssm:${self:provider.stage}-serpro_cnpj_token}
SERPRO_CPF_TOKEN: ${ssm:${self:provider.stage}-serpro_cpf_token}
VINDI_TOKEN: ${ssm:${self:provider.stage}-vindi_token}
ZENVIA_KEY: ${ssm:${self:provider.stage}-zenvia_key}
ZENVIA_TOKEN: ${ssm:${self:provider.stage}-zenvia_token}
PROTHEUS_KEY: ${ssm:${self:provider.stage}-protheus_key}
PROTHEUS_TOKEN: ${ssm:${self:provider.stage}-protheus_token}
LICENCIADOR_USER: ${ssm:${self:provider.stage}-licenciador_user}
LICENCIADOR_PASS: ${ssm:${self:provider.stage}-licenciador_pass}