FROM protheus-base
LABEL maintainer="Wagner Mobile Costa <mobile.costa@gmail.com>"
COPY ./root/ /

# Porta do monitoramento do License Server.
EXPOSE 1234/tcp

# Porta HTML do License Server.
EXPOSE 80/tcp
