services:
  c1:
    image: node-api
    container_name: contador_1
    ports:
      - "3000:3000"
  c2:
    image: node-api
    container_name: contador_2
    ports:
      - "3001:3000"      
  c3:
    image: node-api
    container_name: contador_3
    ports:
      - "3002:3000"            