Resources:
  DocumentsBureau:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.stage}_documents_bureau
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
    # Set the capacity based on the stage
      BillingMode: PAY_PER_REQUEST

  VindiWebhookTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.stage}_vindi_webhook
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: type
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: typeIndex
          KeySchema:
            - AttributeName: type
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY
      BillingMode: PAY_PER_REQUEST
  
  ChargesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.stage}_charges
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: bill_id
          AttributeType: S
      KeySchema: 
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: billIndex
          KeySchema:
            - AttributeName: bill_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  PeriodsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.stage}_periods
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: subscription_id
          AttributeType: S
      KeySchema: 
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: subscriptionAndStartIndex
          KeySchema:
            - AttributeName: subscription_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      
  CustomersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.stage}_customers
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
        - AttributeName: registry_code
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: emailIndex
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY
        - IndexName: registryCodeIndex
          KeySchema:
            - AttributeName: registry_code
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY
      BillingMode: PAY_PER_REQUEST

  PhoneCustomerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.stage}_customers_phone
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  SubscriptionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.stage}_subscriptions
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: customer_id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: customerIndex
          KeySchema:
            - AttributeName: customer_id
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY
      BillingMode: PAY_PER_REQUEST

  PlansTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.stage}_plans
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
    # Set the capacity based on the stage
      BillingMode: PAY_PER_REQUEST

  DiscountsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.stage}_discounts
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
    # Set the capacity based on the stage
      BillingMode: PAY_PER_REQUEST

  TwoFactorsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.stage}_token_twofactors
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
    # Set the capacity based on the stage
      BillingMode: PAY_PER_REQUEST

  InvoicesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.stage}_invoices
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
    # Set the capacity based on the stage
      BillingMode: PAY_PER_REQUEST

  PayloadsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.stage}_payloads
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
    # Set the capacity based on the stage
      BillingMode: PAY_PER_REQUEST

  EventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.stage}_events
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    # Set the capacity based on the stage
      # BillingMode: PAY_PER_REQUEST


  BankSlipTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.stage}_bank_slip
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
    # Set the capacity based on the stage
      BillingMode: PAY_PER_REQUEST

  ErrorInterfaceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.stage}_errors_interfaces
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    # Set the capacity based on the stage
      # BillingMode: PAY_PER_REQUEST

  ErrorArchiveTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.stage}_errors_archive
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
    # Set the capacity based on the stage
      BillingMode: PAY_PER_REQUEST

  BillsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.stage}_bills
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
    # Set the capacity based on the stage
      BillingMode: PAY_PER_REQUEST

  PendingPurchaseTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.stage}_pending_purchase
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
    # Set the capacity based on the stage
      BillingMode: PAY_PER_REQUEST
  
  ResellerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.stage}_resellers
      AttributeDefinitions:
        - AttributeName: reseller_id
          AttributeType: S
      KeySchema:
        - AttributeName: reseller_id
          KeyType: HASH
    # Set the capacity based on the stage
      BillingMode: PAY_PER_REQUEST

  VindiErrorsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.stage}_vindi_errors
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
    # Set the capacity based on the stage
      BillingMode: PAY_PER_REQUEST

  LicenciadorErrorsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.stage}_licenciador_errors
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
    # Set the capacity based on the stage
      BillingMode: PAY_PER_REQUEST
  
  StoreErrorsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.stage}_store_errors
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
    # Set the capacity based on the stage
      BillingMode: PAY_PER_REQUEST

  ProtheusErrorsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.stage}_protheus_errors
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
    # Set the capacity based on the stage
      BillingMode: PAY_PER_REQUEST

  EmpoderaErrorsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.stage}_empodera_errors
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
    # Set the capacity based on the stage
      BillingMode: PAY_PER_REQUEST

  MessageTemplateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.stage}_message_template
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: template_type
          AttributeType: S
      KeySchema: 
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: message_template_type_idx
          KeySchema:
            - AttributeName: template_type
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST