services:
  c1:
    build: .
    container_name: html_1
    ports:
      - "8081:8080"
    volumes:
      - /dev/git/mobilecosta/docker/html:/usr/src/app
  c2:
    build: .
    container_name: html_2
    ports:
      - "8082:8080"
    volumes:
      - especial:/usr/src/app

volumes:      
  especial:
    external: true