services:
  c1:
    build: .
    container_name: nodeapi_1
    ports:
      - "3000:3000"
    volumes:
      - /dev/git/mobilecosta/docker/node_api:/usr/src/app
  c2:
    build: .
    container_name: nodeapi_2
    ports:
      - "3001:3000"
    volumes:
      - container-volume:/usr/src/app

volumes:      
  container-volume: